
# Generated by CodiumAI
from src.preprocessing import read_in_raw_trade_data
from src.preprocessing import read_in_raw_production_data
import pandas as pd

import pytest


def test_returns_correct_dataframe_trade():
    result = read_in_raw_trade_data(testing=True)
    assert isinstance(result, pd.DataFrame)
    # This is the shape of the Oceanian subset of the data.
    assert result.shape == (215548, 84)


def test_returns_correct_dataframe_production():
    result = read_in_raw_production_data()
    assert isinstance(result, pd.DataFrame)
    # This is the shape of the complete dataset.
    assert result.shape == (79297, 70)


