from src.utils import jaccard_index
import os
import pandas as pd

prefix = f"data{os.sep}preprocessed_data{os.sep}integrated_model"
path = prefix + f"{os.sep}prod_trade"
suffix = "_Y2020_Global_production.csv"  # TODO: generalise for any year/region
supply_items = set(
    [
        f[: -len(suffix)]
        for f in os.listdir(path)
        if os.path.isfile(os.path.join(path, f)) and "production" in f
    ]
)
xls = pd.ExcelFile(prefix + f"{os.sep}from_IM{os.sep}Supplemental_Data.xlsx")
nutrition = pd.read_excel(xls, "Nutrition")[["Item", "Calories", "Protein", "Fat"]]
nutrition_items = set(nutrition["Item"].dropna().unique())
missing_items = supply_items.difference(nutrition_items)
guessed_matches = {
    mis_item: max(nutrition_items, key=lambda it: jaccard_index(it, mis_item))
    for mis_item in missing_items
}
# wrongle guessed found manually with:
# wrongly_guessed = []
# for mi, gm in guessed_matches.items():
#     print(mi, "==", gm)
#     if input("yay? ") == "n":
#         wrongly_guessed.append(mi)
# print(wrongly_guessed)
wrongly_guessed = [
    "Edible offals of camels and other camelids, fresh, chilled or frozen",
    "pig",
    "Whole milk, evaporated",
    "Broad beans and horse beans, green",
    "Pyrethrum, dried flowers",
    "Cheese (All Kinds)",
    "Meat of geese, fresh or chilled",
    "Evaporated & Condensed Milk",
    "Raw hides and skins of buffaloes",
    "Whole milk, condensed",
    "Ducks",
    "Goats",
    "Raw hides and skins of sheep or lambs",
    "Jute, raw or retted",
    "Buffalo fat, unrendered",
    "Plantains and cooking bananas",
    "Camels",
    "Other vegetables, fresh n.e.c.",
    "Edible offal of goat, fresh, chilled or frozen",
    "Roots and Tubers, Total",
    "Poultry Birds",
    "Other camelids",
    "Oilcrops, Oil Equivalent",
    "Chestnuts, in shell",
    "Peppermint, spearmint",
    "Edible roots and tubers with high starch or inulin content, n.e.c., fresh",
    "Geese",
    "Pomelos and grapefruits",
    "Meat of other domestic rodents, fresh or chilled",
    "Palm oil",
    "Safflower-seed oil, crude",
    "Other oil seeds, n.e.c.",
    "Beeswax",
    "Raw milk of sheep",
    "Other fibre crops, raw, n.e.c.",
    "Meat of rabbits and hares, fresh or chilled",
    "Rape or colza seed",
    "Goat fat, unrendered",
    "Meat of turkeys, fresh or chilled",
    "Chickens",
    "Sheep",
    "Cabbages",
    "Game meat, fresh, chilled or frozen",
    "Cereals, primary",
    "Balata, gutta-percha, guayule, chicle and similar natural gums in primary forms or in plates, sheets or strip",
    "Edible offal of buffalo, fresh, chilled or frozen",
    "Sheep and Goats",
    "Cattle fat, unrendered",
    "Ginger, raw",
    "Raw hides and skins of goats or kids",
    "Other fruits, n.e.c.",
    "Butter and Ghee",
    "Meat of asses, fresh or chilled",
    "Meat of cattle with the bone, fresh or chilled",
    "Snails, fresh, chilled, frozen, dried, salted or in brine, except sea snails",
    "Pig fat, rendered",
    "Mules and hinnies",
    "Chillies and peppers, dry (Capsicum spp., Pimenta spp.), raw",
    "Other nuts (excluding wild edible nuts and groundnuts), in shell, n.e.c.",
    "Ramie, raw or retted",
    "Kapok fibre, raw",
    "Meat, Poultry",
    "Asses",
    "Green garlic",
    "Skim milk of cows",
    "Groundnuts, excluding shelled",
    "Meat of pigeons and other birds n.e.c., fresh, chilled or frozen",
    "Eggs Primary",
    "Maize (corn)",
    "Cloves (whole stems), raw",
    "Rabbits and hares",
    "Cotton lint, ginned",
    "Milk, Total",
    "Oil of linseed",
    "Meat of ducks, fresh or chilled",
    "Onions and shallots, dry (excluding dehydrated)",
    "Sheep fat, unrendered",
    "Bees",
    "Cassava, fresh",
    "Raw hides and skins of cattle",
    "Kenaf, and other textile bast fibres, raw or retted",
    "Abaca, manila hemp, raw",
    "Taro",
    "Other berries and fruits of the genus vaccinium n.e.c.",
    "Cattle and Buffaloes",
    "Hop cones",
    "Citrus Fruit, Total",
    "Edible offal of cattle, fresh, chilled or frozen",
    "Meat of buffalo, fresh or chilled",
    "Meat of goat, fresh or chilled",
    "Silk-worm cocoons suitable for reeling",
    "Cottonseed oil",
    "Lentils, dry",
    "Coconuts, in shell",
    "Meat of sheep, fresh or chilled",
    "Skim Milk & Buttermilk, Dry",
    "Sheep and Goat Meat",
    "Other citrus fruit, n.e.c.",
    "True hemp, raw or retted",
    "Meat of chickens, fresh or chilled",
    "Other meat n.e.c. (excluding mammals), fresh, chilled or frozen",
    "Meat of camels, fresh or chilled",
    "Maté leaves",
    "Skim milk and whey powder",
    "Cheese from milk of sheep, fresh or processed",
    "Chillies and peppers, green (Capsicum spp. and Pimenta spp.)",
    "Edible offal of sheep, fresh, chilled or frozen",
    "Fruit Primary",
    "Meat of mules, fresh or chilled",
    "Meat of pig with the bone, fresh or chilled",
    "Meat of other domestic camelids, fresh or chilled",
    "Coir, raw",
    "Flax, processed but not spun",
    "Sunflower-seed oil, crude",
    "Other stimulant, spice and aromatic crops, n.e.c.",
    "Sugar Crops Primary",
    "Raw milk of buffalo",
    "Cinnamon and cinnamon-tree flowers, raw",
    "Treenuts, Total",
    "Edible offal of pigs, fresh, chilled or frozen",
    "Other beans, green",
    "Other pulses n.e.c.",
    "Shorn wool, greasy, including fleece-washed shorn wool",
    "Mixed grain",
    "Horses",
    "Green tea (not fermented), black tea (fermented) and partly fermented tea, in immediate packings of a content not exceeding 3 kg",
    "Oil of sesame seed",
    "Unmanufactured tobacco",
    "Natural rubber in primary forms",
    "Locust beans (carobs)",
    "Sisal, raw",
    "Cattle",
    "Buffalo",
    "Raw milk of cattle",
    "Raw cane or beet sugar (centrifugal only)",
    "Seed cotton, unginned",
    "Other stone fruits",
    "Oilcrops, Cake Equivalent",
    "Edible offals of horses and other equines,  fresh, chilled or frozen",
    "Rapeseed or canola oil, crude",
    "Green corn (maize)",
    "Horse meat, fresh or chilled",
    "Fibre Crops, Fibre Equivalent",
    "Agave fibres, raw, n.e.c.",
    "Meat, Total",
    "Bambara beans, dry",
    "Coconut oil",
    "Chick peas, dry",
    "Raw silk (not thrown)",
    "Vegetables Primary",
    "Pulses, Total",
    "Cantaloupes and other melons",
    "Pistachios, in shell",
    "Beef and Buffalo Meat, primary",
    "Tea leaves",
]
guessed_matches = {k: v for k, v in guessed_matches.items() if k not in wrongly_guessed}
